## Fundamental Matriks
Untuk pengingat, array merupakan salah satu jenis *struktur data linear* dan terdiri dari *kumpulan elemen bertipe data sama* dengan *indeks yang berurutan atau linear*. Sebenarnya, array adalah **jenis struktur data 1 dimensi** yang menyimpan semua datanya secara linear. Pada materi ini, kita akan mempelajari **jenis array 2 dimensi**, yakni **matriks**.

Matriks pada matematika merupakan himpunan yang terdiri dari bilangan atau elemen **berdasarkan baris dan kolom**. Dalam matematika, struktur matriks sebagai berikut:

```
    |0 1 0 0 0| -> Baris ke-1
    |4 2 2 0 0| -> Baris ke-2
A = |2 4 2 0 0| -> Baris ke-3
    |1 1 2 0 0| -> Baris ke-4
    |0 0 1 2 1| -> Baris ke-5

     kolom 1-5
```

Contoh matriks dalam matematika *beragam jenisnya*, beberapa di antaranya sebagai berikut:

1. Matriks Pengukuran

    Matriks pengukuran adalah jenis matriks dengan indeks (i, j) yang **merepresentasikan suatu titik koordinat**. Setiap elemen dari matriks ini merepresentasikan **hasil pengukuran** pada suatu titik koordinat tertentu dan *termasuk bilangan real atau tipe data float*.

2. Matriks Satuan

    Selanjutnya adalah matriks satuan dengan **elemen bernilai hanya 0 atau 1**. Setiap elemen matriks ini *bertipe data integer*.

Anda pun dapat **melakukan berbagai operasi pada matriks**, seperti *penjumlahan*, *perkalian*, menentukan *determinan*, *transpose*, dan sebagainya. Bahkan matriks juga dapat dipakai untuk persoalan algoritmik, yakni untuk menyimpan informasi yang cirinya ditentukan oleh **dua dimensi atau baris dan kolom**, seperti *cell pada spreadsheet*.

Sementara itu dalam pemrograman, matriks adalah **kumpulan data yang diatur dalam bentuk tabel dua dimensi dengan setiap elemennya terdefinisi berdasarkan baris dan kolom**. Matriks dalam pemrograman diimplementasikan **menggunakan array dua dimensi**. Bahkan dalam Python, matriks dapat diimplementasikan menggunakan *nested list* atau *list di dalam list*.

In [22]:
# Membuat matriks dengan nested list
matrix = [[1,2,3],
          [4,5,6],
          [7,8,9]]

print(matrix)
print(matrix[1][2]) # Metode indexing
print(matrix[2][0:3:1]) # Metode slicing

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
6
[7, 8, 9]


Matriks dalam pemrograman dapat kita simpulkan sebagai berikut.

1. Matriks adalah kumpulan data yang diatur dalam bentuk **tabel dua dimensi** dengan setiap elemennya terdefinisi berdasarkan *baris dan kolom*.
2. Setiap elemen matriks dapat diakses melalui **metode indexing** jika kedua indeks telah diketahui.
3. Elemen matriks dideklarasikan **memiliki tipe homogen** yang artinya elemen tersebut harus mempunyai **tipe data yang sama**. Jika elemen tersebut adalah bilangan real, seluruh elemen lainnya pun adalah bilangan real. Walaupun dalam list Python Anda dapat membuat matriks dengan tipe data berbeda, alangkah lebih baik jika tetap mengikuti aturan ini.

Namun, perlu diingat bahwa mendeklarasikan matriks menggunakan list **sangat memakan banyak memori**. Masih ingatkah Anda dengan materi array yang menyatakan bahwa setiap nilai atau elemen dalam list akan disimpan pada masing-masing tempat memori? Hal ini berlaku juga pada matriks.

Oleh karena itu, menggunakan nested list sebagai matriks dianggap cara yang cukup praktis, tetapi **tidak efektif dalam mengelola penyimpanan memori**. Programmer Python biasanya menggunakan **library tambahan seperti NumPy** untuk membuat matriks dengan jumlah elemen besar. Library NumPy sering dipakai oleh programmer Python untuk melakukan tugas-tugas dalam *ranah science* dan *engineering* karena dianggap memiliki **penggunaan penyimpanan memori yang efisien**.

In [31]:
import numpy as np # Mengakses library NumPy

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Implementasi Matriks pada Python

### Deklarasi Matriks
Ada **dua cara** untuk mendeklarasikan matriks menggunakan Python sebagai berikut:

1. Deklarasi sekaligus inisialisasi nilai matriks.

    Cara pertama adalah **mendeklarasikan matriks sekaligus menginisialisasikan nilainya** dengan ukuran N baris dan M Kolom (NxM). Cara ini dilakukan jika kita telah mengetahui nilai yang perlu diberikan.

    ```
    new_matrix = [[val-11, val-12, ..., val-1m],
                  [val-21, val-22, ..., val-2m],
                   ...
                  [val-n1, val-n2, ..., val-nm]]
    ```

2. Deklarasi dengan nilai default.

    Cara kedua adalah **mendeklarasikan matriks dengan nilai default**. Sebagaimana materi array, nilai default ditentukan oleh kesepakatan bersama sesuai kebutuhan dengan nilainya di luar rentang yang ditentukan. Cara kedua ini **melibatkan list comprehension** yang sama seperti pada materi array.

    Struktur dari deklarasi dengan nilai default sebagai berikut (misal jumlah baris dan kolom = n dan m):

    `new_matrix = [[default_value for b in range(m)] for a in range(n)]`

In [33]:
# Deklarasi matrix default element dengan list comprehension
# Matriks berukuran 5 baris dan 5 kolom
import numpy as np

matrix = np.array([[0 for b in range(5)] for a in range(5)])

print(matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


### Akses Elemen Matriks
Mengakses elemen dari matriks, perlu mengetahui indeks dari baris dan kolom. Seperti berikut:

`matrix[index_baris][index_kolom]`

INGAT INDEKS SELALU BERAWAL DARI 0

In [65]:
import numpy as np

matrix = np.array([[a*b*2 for b in range(1, 6)] for a in range(1, 6)])

print(matrix, '\n')
print(matrix[2][3]) # Mengakses dengan metode indexing
print(matrix[3][2:]) # Mengakses dengan metode slicing

[[ 2  4  6  8 10]
 [ 4  8 12 16 20]
 [ 6 12 18 24 30]
 [ 8 16 24 32 40]
 [10 20 30 40 50]] 

24
[24 32 40]


## Operasi Matriks pada Python
Dalam matematika ataupun pemrograman, operasi matriks dapat melibatkan **dua matriks** sekaligus atau pun **satu matriks** saja. Beberapa operasi tersebut di antaranya sebagai berikut:

1. Operasi 1 matriks.

    * Menghitung **total** semua elemen matriks.
    * **Mengalikan** elemen matriks dengan konstanta.
    * **Transpose** matriks.
    * **Inverse** matriks.
    * Menentukan **determinan**, dan sebagainya.

2. Operasi 2 matriks.

    * **Menambahkan** dua matriks.
    * **Mengalikan** dua matriks.
    * **Pembagian** dua matriks, dan sebagainya.

In [82]:
import numpy as np

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f'Matriks original:\n{matrix}\n')

new_matrix = np.array([[0 for b in range(3)] for a in range(3)]) # Membuat matriks baru dengan nilai default 0, guna menampung matriks baru

for c in range(3): # Perkalian skalar tiap elemen matriks
    for d in range(3):
        new_matrix[c][d] = matrix[c][d] * 2

print(f'Matriks setelah dikalikan skalar 2:\n{new_matrix}')

Matriks original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriks setelah dikalikan skalar 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [83]:
# Cara lebih simple menggunakan fungsi dari NumPy
import numpy as np

matrix = np.array([[5,0],[1,-2]])
new_matrix = matrix * 2 # Perkalian skalar menggunakan library NumPy

print(new_matrix)

[[10  0]
 [ 2 -4]]
